In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("house_price_full.csv")
df.head()

bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [5]:
X = df.copy()
Y = X.pop('price')
X, Y

(     bedrooms  sqft_living
 0           3         1340
 1           5         3650
 2           3         1930
 3           3         2000
 4           4         1940
 ..        ...          ...
 494         4         3040
 495         5         4530
 496         3         1370
 497         3         1940
 498         3         1040
 
 [499 rows x 2 columns],
 0       313000
 1      2384000
 2       342000
 3       420000
 4       550000
         ...   
 494     647000
 495     950000
 496     185000
 497     335000
 498     210000
 Name: price, Length: 499, dtype: int64)

In [6]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

Y = np.log(Y)

X,Y

(array([[-4.33197643e-01, -7.53257537e-01],
        [ 1.67573527e+00,  1.45733017e+00],
        [-4.33197643e-01, -1.88648555e-01],
        [-4.33197643e-01, -1.21661048e-01],
        [ 6.21268815e-01, -1.79078911e-01],
        [-1.48766410e+00, -1.19346115e+00],
        [-1.48766410e+00, -7.43687893e-01],
        [ 6.21268815e-01,  5.57783659e-01],
        [-4.33197643e-01,  2.89833634e-01],
        [ 6.21268815e-01, -5.81003949e-01],
        [-4.33197643e-01, -3.99180718e-01],
        [ 6.21268815e-01,  7.58746178e-01],
        [-4.33197643e-01,  1.94137196e-01],
        [-4.33197643e-01, -9.92498631e-01],
        [ 1.67573527e+00,  7.49176535e-01],
        [-4.33197643e-01, -8.87232550e-01],
        [-4.33197643e-01, -5.33155730e-01],
        [ 6.21268815e-01,  9.40569410e-01],
        [-4.33197643e-01, -7.24548606e-01],
        [-4.33197643e-01, -9.06371837e-01],
        [-4.33197643e-01,  1.08010402e-01],
        [ 6.21268815e-01, -6.47991456e-01],
        [-4.33197643e-01, -3.609

In [7]:
df_scaled = pd.DataFrame(X)
df_scaled

0         1
0   -0.433198 -0.753258
1    1.675735  1.457330
2   -0.433198 -0.188649
3   -0.433198 -0.121661
4    0.621269 -0.179079
..        ...       ...
494  0.621269  0.873582
495  1.675735  2.299459
496 -0.433198 -0.724549
497 -0.433198 -0.179079
498 -0.433198 -1.040347

[499 rows x 2 columns]

In [8]:
x1,x2 = df_scaled.iloc[0]
x1,x2

(-0.43319764280264655, -0.7532575369937701)

In [9]:
x = tf.constant([[x1,x2]],dtype=tf.float32)
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.43319765, -0.7532575 ]], dtype=float32)>

In [10]:
w1 = tf.Variable([0.2],dtype=tf.float32)
w2 = tf.Variable([0.15],dtype=tf.float32)
b = tf.Variable([0.1],dtype=tf.float32)
z = w1*x1 + w2*x2 + b
h = tf.math.sigmoid(z)
print("Output from 1st neuron is: ",h)

Output from 1st neuron is:  tf.Tensor([0.47511354], shape=(1,), dtype=float32)


In [11]:
## layer1 weights
# neuron1
b1 = tf.Variable([0.1])
w11 = tf.Variable([0.2])
w12 = tf.Variable([0.15])
#neuron2
b2 = tf.Variable([0.25])
w21 = tf.Variable([0.5])
w22 = tf.Variable([0.6])
## forward pass
# neuron 1
z1 = b1+w11*x1+w12*x2
h1 = tf.math.sigmoid(z1)
print("The output from the first neuron is",h1)
## forward pass
# neuron 2
z2 = b2+w21*x1+w22*x2
h2 = tf.math.sigmoid(z2)
print("The output from the second neuron is",h2)
## layer2 weights
b1 = tf.Variable([0.4])
w11 = tf.Variable([0.3])
w12 = tf.Variable([0.2])
## forward pass
# second layer
z1 = b1+w11*h1+w12*h2
h1 = z1
print("The output from the first neuron is",h1)

The output from the first neuron is tf.Tensor([0.47511354], shape=(1,), dtype=float32)
The output from the second neuron is tf.Tensor([0.39686295], shape=(1,), dtype=float32)
The output from the first neuron is tf.Tensor([0.62190664], shape=(1,), dtype=float32)


In [12]:
y_true = Y[0]
y_pred = h1.numpy()

In [13]:
#loss
L = 0.5*(y_true - y_pred)**2
print("The MSE error is",L)

The MSE error is [72.38514]
